vich_uploader:
    db_driver: orm # Utilisez "odm" si vous travaillez avec MongoDB
    mappings:
        user_avatar:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user_cvs:
            uri_prefix: /uploads/cvs
            upload_destination: '%kernel.project_dir%/public/uploads/cvs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
